name: Python test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.12']
        numpy-version: ['1.26.4']
        scipy-version: ['1.15.2']
        openmdao-version: ['3.38.0']
      fail-fast: false
    env:
      OMP_NUM_THREADS: 1
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Setup conda for Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        conda-remove-defaults: true
        channels: conda-forge

    - name: Install dependencies
      run: |
        conda install numpy==${{ matrix.numpy-version }} scipy==${{ matrix.scipy-version }}
        python -m pip install openmdao==${{ matrix.openmdao-version }}
        python -m pip install jax
        python -m pip install testflo

    - name: List Python and package info
      run: |
        python --version
        python -m pip list
        conda list

    - name: Run tests in `dcfoil` folder
      run: |
        testflo dcfoil