# This is a basic workflow to help you get started with Actions

name: Unit tests CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.7.3'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project=. test/run_tests.jl
    
  build-macOS:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.7.3'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project=. test/run_tests.jl
